### ISSUE TITLE
Remove DOM factories for React v16

### ISSUE THREAD

**Issue by jfsiii** [stevelacy/react-datagrid2#1]
React 15 prints this warning:

> Warning: Accessing factories like React.DOM.div has been deprecated and will be removed in v16.0+. Use the react-dom-factories package instead.  Version 1.0 provides a drop-in replacement. For more info, see https://fb.me/react-dom-factories

So, code like
```
React.DOM.input(...)
```

needs to become something like

```
import DOM from 'react-dom-factories'
DOM.input(...)
```

or, perhaps

```
import { input } from 'react-dom-factories'
input(...)
```

**Comment by stevelacy** [comment]
fe479ead23b3037df5d01deece7cb6da17ee98f5 🎉
