### ISSUE TITLE
HandleWheel error

### ISSUE THREAD

**Issue by PetrSnobelt** [stevelacy/react-datagrid2#6]
Hi I try this wersion with nextjs and react 16.2 and I have lot of errors in handleWheel function of react-virtual-scroller2

it on last line of of this code 
```
key: 'handleWheel',
    value: function handleWheel(event) {

      var props = this.props;
```

stacktrace 
```
commons.js:616 Uncaught TypeError: Cannot read property 'props' of undefined
    at handleWheel (index.js:279)
    at HTMLUnknownElement.callCallback (commons.js:548)
    at Object.invokeGuardedCallbackDev (commons.js:587)
    at Object.invokeGuardedCallback (commons.js:444)
    at Object.invokeGuardedCallbackAndCatchFirstError (commons.js:458)
    at executeDispatch (commons.js:842)
    at executeDispatchesInOrder (commons.js:864)
    at executeDispatchesAndRelease (commons.js:962)
    at executeDispatchesAndReleaseTopLevel (commons.js:973)
    at Array.forEach (<anonymous>)
```

Anyone else tries this with react 16.2?

**Comment by stevelacy** [comment]
We are using this with react 16.2.0 without that issue. 

Can you console.log the `this` in the render function where `handleWheel` is called?
https://github.com/stevelacy/react-virtual-scroller2/blob/master/dist/react-virtual-scroller.js#L238

**Comment by PetrSnobelt** [comment]
sure, this is undefined

**Comment by PetrSnobelt** [comment]
here is the source of sample page served by nextjs

```
import React, { PureComponent } from 'react'
import DataGrid from 'react-datagrid2'

const defaultColumns = [
  { name: 'id' },
  { name: 'title' },
  { name: 'count' }
]

const createRows = () => {
  let rows = []
  for (let i = 1; i < 1000; i++) {
    rows.push({
      id: i,
      title: 'Title ' + i,
      count: i * 1000
    })
  }

  return rows
}

export default class Grid extends PureComponent {
  render () {
    const gridData = createRows()
    const gridColumns = defaultColumns
    return <DataGrid idProperty='id'
      dataSource={gridData}
      columns={gridColumns}
      style={{height: 400}}
    />
  }
}
```

As soon as I try to scroll, errors occurred. Chrome 64.0.3282.167 (Official Build) (64-bit)

**Comment by PetrSnobelt** [comment]
Interesting on codesandbox it works without problems 
https://codesandbox.io/s/n069yloop

**Comment by PetrSnobelt** [comment]
It must be something with nextjs :-(

**Comment by stevelacy** [comment]
I am wondering... how does nextjs create the scope for the classes?
Is there a way to run nextjs in codesandbox?

**Comment by PetrSnobelt** [comment]
It looks like it can be caused by HMR in dev mode

**Comment by PetrSnobelt** [comment]
I'm just guessing, but maybe react-virtual-scroller2 missing removing listeners. 
Elements should not be added in render...
https://github.com/stevelacy/react-virtual-scroller2/blob/master/src/index.jsx#L149

**Comment by PetrSnobelt** [comment]
I know that it is strange, but when I explicitly bind events to this like this - line 146:
```
if (!hasTouch){
      events.onWheel = this.handleWheel.bind(this)
    } else {
      events.onTouchStart = this.handleTouchStart.bind(this)
    }
``` 
and then scroller at line 342: 
`var onScroll = this.onVerticalScroll.bind(this)`

it starts working even in dev mode

**Comment by stevelacy** [comment]
want to send a PR?

**Comment by PetrSnobelt** [comment]
https://github.com/stevelacy/react-virtual-scroller2/pull/2
